### ISSUE TITLE
Cert name invalid

### ISSUE THREAD

**Issue by bmitchinson** [aholachek/bundle-wizard#14]
Wondering why I'm getting this error from puppeteer that "CERT_NAME_IS_INVALID" when the src code for this script asks puppeteer to ignore HTTPS errors. Maybe it needs to be set to true explicitly?

Ref part of bundle-wizard code: https://github.com/aholachek/bundle-wizard/blob/5c2321374aa7fe04751ef0dd131064a83f8ed909/src/functions/downloadCoverage.js#L71

Here's an implementation where it's set to true: https://github.com/christopherwk210/site-scan/commit/04e88221714c08341ee3df890ea3ca74996d0f86

My error:
![image](https://user-images.githubusercontent.com/33632286/92974965-eed74a80-f44c-11ea-8f14-5b02ae4bda80.png)

**Comment by aholachek** [comment]
The error you're seeing is slightly different from the errors users used to see when there was no option to ignore https errors (see this issue for reference: https://github.com/aholachek/bundle-wizard/issues/1) I don't know if this is actually a bundle wizard issue or if there is possibly something wrong with the local certificate. Sorry I can't be more help, please let me know if you end up figuring it out.
