### ISSUE TITLE
Potential Bugs and Anti-Patterns in the Codebase

### ISSUE THREAD

**Issue by HarshCasper** [aholachek/bundle-wizard#19]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/bundle-wizard/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Missing Key Prop [here](https://deepsource.io/gh/HarshCasper/bundle-wizard/issue/JS-0414/)
- Unused Variables [here](https://deepsource.io/gh/HarshCasper/bundle-wizard/issue/JS-0128/)
- Empty Block Statements [here](https://deepsource.io/gh/HarshCasper/bundle-wizard/issue/JS-0009/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by aholachek** [comment]
Hi, thanks for doing this. I'm not too concerned about the examples you highlighted so I'm going to close this issue.
