### ISSUE TITLE
[Feature Request] Ability to specify port

### ISSUE THREAD

**Issue by ricokahler** [aholachek/bundle-wizard#22]
Would you be open to accepting PRs to specify the port manually? (e.g. `--port`) I don't think `get-port` is resolving correctly on my machine.

I'll start a next.js server on port 3000 and bundle-wizard starts on port 3000 too (i didn't know that was possible!)

btw, love the project!

**Comment by aholachek** [comment]
Hi, that sounds annoying, for sure I would be happy to accept a pr that added a port option.
