### ISSUE TITLE
"No valid exports main found"

### ISSUE THREAD

**Issue by bmitchinson** [aholachek/bundle-wizard#5]
Any idea about this? Not sure what the root of the issue is / how to debug.

```
 ~  npx bundle-wizard https://mitchinson.dev
No valid exports main found for '/Users/bmitchinson/.npm/_npx/2631/lib/node_modules/bundle-wizard/node_modules/uuid'
 ~  npx bundle-wizard mitchinson.dev
No valid exports main found for '/Users/bmitchinson/.npm/_npx/2806/lib/node_modules/bundle-wizard/node_modules/uuid'
```

---

![image](https://user-images.githubusercontent.com/33632286/82013069-f887a780-963e-11ea-88a5-33d804d5c13d.png)

**Comment by aholachek** [comment]
Thank you for making this issue. it seems other people have recently been running into this problem with the `uuid` package:
- https://github.com/facebook/flipper/issues/1144
- https://github.com/strongloop/loopback-next/issues/5381

They suggest upgrading node, I'm not sure if that's a possibility or for you to try out, maybe with nvm.

**Comment by bmitchinson** [comment]
yeah fixed by using node 14. my bad for not trying that.

**Comment by chetan16** [comment]
upgrade your node js version to above v14
