### ISSUE TITLE
Authentication Support

### ISSUE THREAD

**Issue by deasems** [aholachek/bundle-wizard#7]
My application is behind authentication - on initial load the user will get redirected to login through a separate site. 
If I'm reading the docs right that would prevent this tool from working on my app.
Support for this scenario to handle the login, then analyze the site after an authenticated load would be great.

**Comment by aholachek** [comment]
Hi, thanks for flagging this. I'm working on an option to spin up a non-headless version of chrome which will let you do whatever you want to get the app in the right state (e.g. log in as a certain user), and then when you're ready, reload the current page and begin recording performance data. 
I hope to publish a beta version with this option later today or tomorrow, I'll comment here when it's ready in case you'd be willing to test it on your use case.

**Comment by aholachek** [comment]
Hi @deasems, if you get the chance, I'd really appreciate a test run of the new `--interact` flag:

`npx bundle-wizard@beta --interact` will open a non-headless browser window for you to interact with before continuing with the page audit.

Here's the documentation on the flag:

### --interact flag
If you need to do some work in the browser getting the page ready for analysis (perhaps by signing in and then visiting a certain page), use this flag. You will see a browser window that will pop up that you can interact with. When you are ready to proceed, type `y` into the console in response to the waiting prompt to reload the page and start measuring performance.

`npx bundle-wizard --interact`

Note: While this tool does not record any data, it's still recommended from a common sense perspective to enter login information only for test accounts.

**Comment by deasems** [comment]
Hey @aholachek, I tried it out and it worked really well, thanks for adding this! This `--interact` mode also allows me to interact with the site to get coverage on code paths that are behind interaction handlers 👍 

I'm really excited about this tool, it makes bundle analysis and optimization so much more actionable. 

Here's some feedback from my tests:
1. Launching in mobile mode looked somewhat broken in a browser window that was something like 800x600 in size (my app's poor responsive layout also contributed to this) -- there's no functional issue here, it was just visually jarring.

2. The `--desktop` size seems far too small, I'm using [breakpoints](https://developer.microsoft.com/en-us/fluentui#/styles/web/layout) up through 1920px and would generally like to test at least a typical mobile, tablet, and large desktop size

3. I'd be interested some level of support for use in a CI pipeline, for example to bring visibility to code coverage changes in routes affected by a given PR. 
An idea here would be to decouple the core logic from the CLI and make it available as a node module, and add some pluggable script support so I could provide a custom script to automate handling auth and tell the tool when to proceed. Then in a CI pipeline I could write a script that detects routes likely impacted by a PR, run this tool, get some structured results data and report some key values.

Anyway, that's all general feedback. The change here does indeed address the auth scenario - thanks!

**Comment by deasems** [comment]
Oh, I forgot this point:
4. I'm seeing some files show up as white with 'no coverage data'. These are files that are within a bundle that otherwise is listing coverage so it's surprising to have no coverage info, do you have any ideas what might cause this or how to fix?
